// <auto-generated />
using System;
using CreditRiskSystem.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditRiskSystem.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250607225849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditRiskSystem.Common.Models.FinancialData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Код1100")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1110")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1150")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1200")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1210")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1220")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1230")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1240")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1250")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1260")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1300")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1370")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1400")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1500")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1510")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1520")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1530")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1540")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1550")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1600")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1700")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2100")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2110")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2120")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2200")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2210")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2220")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2300")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2330")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2350")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2400")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("FinancialData");
                });

            modelBuilder.Entity("CreditRiskSystem.Common.Models.RiskAssessmentResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltmanRiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AltmanZScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FinancialDataId")
                        .HasColumnType("uuid");

                    b.Property<string>("FulmerRiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FulmerScore")
                        .HasColumnType("double precision");

                    b.Property<double>("OhlsonOScore")
                        .HasColumnType("double precision");

                    b.Property<double>("OhlsonProbability")
                        .HasColumnType("double precision");

                    b.Property<string>("OverallRiskAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpringateRiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SpringateScore")
                        .HasColumnType("double precision");

                    b.Property<double>("ZmijewskiProbability")
                        .HasColumnType("double precision");

                    b.Property<double>("ZmijewskiScore")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА1")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА10")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА11")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА2")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА3")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА4")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА5")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА6")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА7")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА8")
                        .HasColumnType("double precision");

                    b.Property<double>("ДА9")
                        .HasColumnType("double precision");

                    b.Property<double>("П1")
                        .HasColumnType("double precision");

                    b.Property<double>("П2")
                        .HasColumnType("double precision");

                    b.Property<double>("П3")
                        .HasColumnType("double precision");

                    b.Property<double>("П4")
                        .HasColumnType("double precision");

                    b.Property<double>("П5")
                        .HasColumnType("double precision");

                    b.Property<double>("П6")
                        .HasColumnType("double precision");

                    b.Property<double>("П7")
                        .HasColumnType("double precision");

                    b.Property<double>("П8")
                        .HasColumnType("double precision");

                    b.Property<double>("Р1")
                        .HasColumnType("double precision");

                    b.Property<double>("Р2")
                        .HasColumnType("double precision");

                    b.Property<double>("Р3")
                        .HasColumnType("double precision");

                    b.Property<double>("Р4")
                        .HasColumnType("double precision");

                    b.Property<double>("Р5")
                        .HasColumnType("double precision");

                    b.Property<double>("Р6")
                        .HasColumnType("double precision");

                    b.Property<double>("Р7")
                        .HasColumnType("double precision");

                    b.Property<double>("ФУ1")
                        .HasColumnType("double precision");

                    b.Property<double>("ФУ2")
                        .HasColumnType("double precision");

                    b.Property<double>("ФУ3")
                        .HasColumnType("double precision");

                    b.Property<double>("ФУ4")
                        .HasColumnType("double precision");

                    b.Property<double>("ФУ5")
                        .HasColumnType("double precision");

                    b.Property<double>("ФУ6")
                        .HasColumnType("double precision");

                    b.Property<double>("ФУ7")
                        .HasColumnType("double precision");

                    b.Property<double>("ФУ8")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FinancialDataId");

                    b.ToTable("RiskAssessmentResults");
                });

            modelBuilder.Entity("CreditRiskSystem.Common.Models.RiskAssessmentResult", b =>
                {
                    b.HasOne("CreditRiskSystem.Common.Models.FinancialData", "FinancialData")
                        .WithMany()
                        .HasForeignKey("FinancialDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialData");
                });
#pragma warning restore 612, 618
        }
    }
}
