// <auto-generated />
using System;
using CreditRiskSystem.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditRiskSystem.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditRiskSystem.Common.Models.FinancialData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Код1200")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1300")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1370")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1400")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1500")
                        .HasColumnType("double precision");

                    b.Property<double>("Код1600")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2110")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2300")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2330")
                        .HasColumnType("double precision");

                    b.Property<double>("Код2400")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("FinancialData");
                });

            modelBuilder.Entity("CreditRiskSystem.Common.Models.RiskAssessmentResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltmanRiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AltmanZScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FinancialDataId")
                        .HasColumnType("uuid");

                    b.Property<string>("FulmerRiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FulmerScore")
                        .HasColumnType("double precision");

                    b.Property<double>("OhlsonOScore")
                        .HasColumnType("double precision");

                    b.Property<double>("OhlsonProbability")
                        .HasColumnType("double precision");

                    b.Property<string>("OverallRiskAssessment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpringateRiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SpringateScore")
                        .HasColumnType("double precision");

                    b.Property<double>("ZmijewskiProbability")
                        .HasColumnType("double precision");

                    b.Property<double>("ZmijewskiScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FinancialDataId");

                    b.ToTable("RiskAssessmentResults");
                });

            modelBuilder.Entity("CreditRiskSystem.Common.Models.RiskAssessmentResult", b =>
                {
                    b.HasOne("CreditRiskSystem.Common.Models.FinancialData", "FinancialData")
                        .WithMany()
                        .HasForeignKey("FinancialDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialData");
                });
#pragma warning restore 612, 618
        }
    }
}
